name = "DiscreteOrderedMedian"
uuid = "749eb255-e7f0-474c-bf5d-cdfd6b01954b"
authors = ["Maril√®ne Cherkesly <cherkesly.marilene@uqam.ca>", "Claudio Contardo <claudio.contardo@concordia.ca>", "Matthieu Gruson <gruson.matthieu@uqam.ca>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataStructures = "0.18"
GLPK = "1.1.3"
Graphs = "1"
JuMP = "1.21"
MathOptInterface = "1.28"
PrecompileTools = "1.2.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
